project:
  type: website
  output-dir: docs

website:
  title: "lucas-diedrich.github.io"
  navbar:
    search: true
    foreground: "#efefef"
    background: "#059276"
    left:
      - href: index.qmd
        text: Home
      - work.qmd
      - blog.qmd  
    tools: 
      - icon: twitter 
        href: https://twitter.com/lucas__1406/
      - icon: github 
        href: https://github.com/lucas-diedrich

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



